### ISSUE TITLE
Validate time input for search

### ISSUE THREAD

**Issue by andy7809** [googleinterns/step124-2020#33]
We did validation for the signup form, but missed validation of the search form for the mvp. Need to validate the search data to have a proper time before submitting.

**Comment by andy7809** [comment]
@PriyaVarra , continuing our discussion on this thread instead. Currently, I round hours and minutes to the nearest integer instead of rejecting them. Should we reject them and offer a warning, or round the values? If a user type '1.5' in the hour box, would they be ok with places that are 2 hours +/- a little bit? or should we say no, this is wrong, please input 1 hour and 30 minutes.

**Comment by PriyaVarra** [comment]
I think it might be better to restrict it to only integers since they might assume putting 1.5 hours would mean 1 hour and 30 minutes. 

One idea that might work is if we have a regular expression: "let re = /^\d+$/;", then we can do "re.test(event.value.target)" first which will return true if the string only contains integers before using the rest of the validation code as is. If leading and trailing whitespaces might be an issue, then i think "re = /^\s*\d+\s*$/;" should account for that. Let me know what you think!

**Comment by andy7809** [comment]
I agree with this. I will implement integer guarantees for the hour field tomorrow morning.
